export const COUNTRYTABLE=
[["afghanistan","Afghanistan"],
["albania","Albanien"],
["algeria","Algerien"],
["andorra","Andorra"],
["angola","Angola"],
["antigua","Antigua"],
["antigua and barbuda","Antigua und Barbuda"],
["argentina","Argentinien"],
["armenia","Armenien"],
["at","Österreich"],
["au","Australien"],
["australia","Australien"],
["austria","Österreich"],
["azerbaijan","Aserbaidschan"],
["bahrain","Bahrain"],
["bangladesh","Bangladesch"],
["barbados","Barbados"],
["barbuda","Barbuda"],
["be","Belgien"],
["belarus","Weißrussland (Belarus)"],
["belgium","Belgien"],
["belize","Belize"],
["benin","Benin"],
["bhutan","Bhutan"],
["bolivia","Bolivien"],
["bosnia","Bosnien"],
["bosnia and herzegovina","Bosnien und Herzegowina"],
["botswana","Botswana"],
["brazil","Brasilien"],
["brd","Westdeutschland"],
["brunei","Brunei"],
["bulgaria","Bulgarien"],
["burkina faso","Burkina Faso"],
["burma","Myanmar"],
["burundi","Burundi"],
["ca","Kanada"],
["cabo verde","Kap Verde"],
["cambodia","Kambodscha"],
["cameroon","Kamerun"],
["canada","Kanada"],
["cdn","Kanada"],
["central african republic","Zentralafrikanische Republik"],
["ch","Schweiz"],
["chad","Tschad"],
["chile","Chile"],
["china","China"],
["chn","China"],
["colombia","Kolumbien"],
["comoros","Komoren"],
["congo","Kongo"],
["costa rica","Costa Rica"],
["côte d'ivoire","Elfenbeinküste"],
["croatia","Kroatien"],
["cuba","Kuba"],
["cyprus","Zypern"],
["czech republic","Tschechoslowakei"],
["czechoslovakia","Tschechoslowakei"],
["ddr","Ostdeutschland"],
["de","Deutschland"],
["denmark","Dänemark"],
["djibouti","Dschibuti"],
["dk","Dänemark"],
["dominica","Dominica"],
["dominican republic","Dominikanische Republik"],
["east germany","Ostdeutschland"],
["east timor (timor-leste)","Osttimor (Timor-Leste)"],
["ecuador","Ecuador"],
["egypt","Ägypten"],
["el salvador","El Salvador"],
["equatorial guinea","Äquatorialguinea"],
["eritrea","Eritrea"],
["es","Spanien"],
["estonia","Estland"],
["eswatini","Eswatini"],
["ethiopia","Äthiopien"],
["fi","Finnland"],
["fiji","Fidschi"],
["finland","Finnland"],
["fr","Frankreich"],
["france","Frankreich"],
["gabon","Gabun"],
["gb","England"],
["georgia","Georgia"],
["germany","Deutschland"],
["ghana","Ghana"],
["great britain","England"],
["greece","Griechenland"],
["grenada","Grenada"],
["grenadines","Grenadinen"],
["großbritannien","England"],
["guatemala","Guatemala"],
["guinea","Guinea"],
["guinea-bissau","Guinea-Bissau"],
["guyana","Guyana"],
["haiti","Haiti"],
["herzegovina","Herzegowina"],
["honduras","Honduras"],
["hong kong","Hongkong"],
["hu","Ungarn"],
["hungary","Ungarn"],
["iceland","Island"],
["india","Indien"],
["indonesia","Indonesien"],
["iran","Iran"],
["iraq","Irak"],
["ireland","Irland"],
["israel","Israel"],
["italy","Italien"],
["jamaica","Jamaika"],
["japan","Japan"],
["jordan","Jordanien"],
["kazakhstan","Kasachstan"],
["kenya","Kenia"],
["kiribati","Kiribati"],
["korea","Korea"],
["kosovo","Kosovo"],
["kuwait","Kuwait"],
["kyrgyzstan","Kirgisistan"],
["laos","Laos"],
["latvia","Lettland"],
["lebanon","Libanon"],
["lesotho","Lesotho"],
["liberia","Liberia"],
["libya","Libyen"],
["liechtenstein","Liechtenstein"],
["lithuania","Litauen"],
["luxembourg","Luxemburg"],
["macedonia","Mazedonien"],
["madagascar","Madagaskar"],
["malawi","Malawi"],
["malaysia","Malaysia"],
["maldives","Malediven"],
["mali","Mali"],
["malta","Malta"],
["marshall islands","Marshallinseln"],
["mauritania","Mauretanien"],
["mauritius","Mauritius"],
["mexico","Mexiko"],
["micronesia","Mikronesien"],
["moldova","Moldawien"],
["monaco","Monaco"],
["mongolia","Mongolei"],
["montenegro","Montenegro"],
["morocco","Marokko"],
["mozambique","Mosambik"],
["myanmar","Myanmar"],
["namibia","Namibia"],
["nauru","Nauru"],
["nepal","Nepal"],
["netherlands","Niederlande"],
["new zealand","Neuseeland"],
["nicaragua","Nicaragua"],
["niger","Niger"],
["nigeria","Nigeria"],
["nl","Niederlande"],
["north korea","Nordkorea"],
["north macedonia","Nordmazedonien"],
["norway","Norwegen"],
["oman","Oman"],
["pakistan","Pakistan"],
["palau","Palau"],
["palestinian territory","Palästina"],
["panama","Panama"],
["papua new guinea","Papua-Neuguinea"],
["paraguay","Paraguay"],
["peru","Peru"],
["philippines","Philippinen"],
["pl","Polen"],
["poland","Polen"],
["portugal","Portugal"],
["principe","Príncipe"],
["qatar","Katar"],
["romania","Rumänien"],
["russia","Russland"],
["rwanda","Ruanda"],
["saint kitts and nevis","St. Kitts und Nevis"],
["saint lucia","St. Lucia"],
["saint vincent","St. Vincent"],
["saint vincent and the grenadines","St. Vincent und Grenadinen"],
["samoa","Samoa"],
["san marino","San Marino"],
["sao tome","São Tomé"],
["sao tome and principe","São Tomé und Príncipe"],
["saudi arabia","Saudi-Arabien"],
["senegal","Senegal"],
["serbia","Serbien"],
["seychelles","Seychellen"],
["sierra leone","Sierra Leone"],
["singapore","Singapur"],
["slovakia","Slowakei"],
["slovenia","Slowenien"],
["solomon islands","Salomonen"],
["somalia","Somalia"],
["south africa","Südafrika"],
["south korea","Südkorea"],
["spain","Spanien"],
["sri lanka","Sri Lanka"],
["sudan","Sudan"],
["sudan","Sudan"],
["suriname","Suriname"],
["sweden","Schweden"],
["switzerland","Schweiz"],
["syria","Syrien"],
["taiwan","Taiwan"],
["tajikistan","Tadschikistan"],
["tanzania","Tansania"],
["thailand","Thailand"],
["the bahamas","Die Bahamas"],
["the gambia","Gambia"],
["togo","Togo"],
["tonga","Tonga"],
["tr","Türkei"],
["trinidad and tobago","Trinidad und Tobago"],
["tunisia","Tunesien"],
["turkey","Türkei"],
["turkmenistan","Turkmenistan"],
["tuvalu","Tuvalu"],
["uganda","Uganda"],
["ukraine","Ukraine"],
["united arab emirates","Vereinigte Arabische Emirate"],
["united kingdom","England"],
["united states","USA"],
["united states of america","USA"],
["uruguay","Uruguay"],
["us","USA"],
["uzbekistan","Usbekistan"],
["vanuatu","Vanuatu"],
["vatican city","Vatikanstadt"],
["venezuela","Venezuela"],
["vietnam","Vietnam"],
["west germany","Westdeutschland"],
["yemen","Jemen"],
["yugoslavia","Jugoslawien"],
["za","Südafrika"],
["zambia","Sambia"],
["zimbabwe","Simbabwe"]
]
